version: '2'
services:
  mysql:
        image: mysql:8.0
        container_name: mysql-server-80
        command: --default-authentication-plugin=mysql_native_password
#        working_dir: /application
        volumes:
          - .:/application
        restart: always #restart mysql when container is up
        environment:
          - MYSQL_ROOT_PASSWORD=.sweetpwd.
          - MYSQL_DATABASE=my_db
          - MYSQL_USER=db_user
          - MYSQL_PASSWORD=.mypwd
        ports:
          - "8082:3306"
  website:  #name can be anything
    container_name: php72
    build:     #similar to docker build
      context: .  #docker file location
    volumes:
      - public/:/var/www/html #copy public folder to /var/www/htm location
    ports:
      - 8000:80
    depends_on:
      - mysql #inorder to run website service mysql must be up
